# Default values for ecr-credential-updater.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

nameOverride: ""
fullnameOverride: ""

serviceAccount:
accountId:
aws:
  region:
  secretKey:
  accessKeyId: